version: 2.1
jobs:
  validate:
    docker:
      - image: garethr/kubeval
    working_directory: /tmp/workspace/kubernetes
    steps:
      - checkout
      - run:
          name: Validate kubernetes manifests
          command: kubeval nexus/