version: 2.1
jobs:
  validate:
    docker:
      - image: garethr/kubeval
    working_directory: /tmp/workspace/kubernetes
    steps:
      - checkout
      - run:
          name: test
          command: ls
      - run:
          name: Validate kubernetes manifests
          command: kubeval -d /tmp/workspace/kubernetes/nexus/
      - run:
          name: Validate kubernetes manifests
          command: kubeval -d /tmp/workspace/kubernetes/emby/
      - run:
          name: Validate kubernetes manifests
          command: kubeval -d /tmp/workspace/kubernetes/kubernetes-dashboard/
      - run:
          name: Validate kubernetes manifests
          command: kubeval -d /tmp/workspace/kubernetes/nexus/
  deploy-kubernetes:
    docker:
      - image: devth/helm:latest
    environment:
      KUBECONFIG: /kubeconfig
    steps:
      - checkout
      # - run:
      #     command: apk --no-cache add curl
      # - run:
      #     name: install kubectl
      #     command: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
      - run:
          name: set up kubeconfig
          command: |
            echo $KUBECONFIG_FILE | base64 -d >> /kubeconfig
      - run:
          name: set up helm
          command: |
            helm repo add stable https://kubernetes-charts.storage.googleapis.com
            helm repo add jetstack https://charts.jetstack.io
            helm repo update
      - run:
          name: install metallb
          command:
             helm upgrade metallb stable/metallb --namespace kube-system --set configInline.address-pools[0].name=default --set configInline.address-pools[0].protocol=layer2 --set configInline.address-pools[0].addresses[0]=192.168.0.240-192.168.0.250  --install 
      - run:
          name: install nginx
          command: helm upgrade nginx-ingress stable/nginx-ingress --namespace kube-system --set defaultBackend.enabled=false --install
      - run:
          name: install cert-manager
          command: |
            kubectl apply -f cert-manager/namespace.yaml
            kubectl apply -f cert-manager/
            helm upgrade cert-manager jetstack/cert-manager --namespace cert-manager --version 0.16.0

workflows:
  version: 2.1
  validate:
    jobs:
      - validate
      - deploy-kubernetes:
          requires:
            - validate
          filters:
            branches:
              only: master
        