version: 2.1
jobs:
  validate:
    docker:
      - image: garethr/kubeval
    working_directory: /tmp/workspace/kubernetes
    steps:
      - checkout
      - run:
          name: test
          command: ls
      - run:
          name: Validate kubernetes manifests
          command: kubeval /tmp/workspace/kubernetes/*
workflows:
  version: 2.1
  validate:
    jobs:
      - validate