version: 2.1
jobs:
  validate-kubernetes-manifests:
    docker:
      - image: garethr/kubeval
    working_directory: /tmp/workspace/kubernetes
    steps:
      - checkout
      # - run:
      #     name: Validate cert-manager manifests
      #     command: kubeval -d /tmp/workspace/kubernetes/cert-manager/
      - run:
          name: Validate emby manifests
          command: kubeval -d /tmp/workspace/kubernetes/emby/
      - run:
          name: Validate kubernetes-dashborad manifests
          command: kubeval -d /tmp/workspace/kubernetes/kubernetes-dashboard/
      - run:
          name: Validate nexus manifests
          command: kubeval -d /tmp/workspace/kubernetes/nexus/
      - run:
          name: Validate nextcloud manifests
          command: kubeval -d /tmp/workspace/kubernetes/nextcloud/
  deploy-kubernetes:
    docker:
      - image: devth/helm:latest
    environment:
      KUBECONFIG: /kubeconfig
    steps:
      - checkout
      # - run:
      #     command: apk --no-cache add curl
      # - run:
      #     name: install kubectl
      #     command: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
      - run:
          name: set up kubeconfig
          command: |
            echo $KUBECONFIG_FILE | base64 -d >> /kubeconfig
      - run:
          name: set up helm
          command: |
            helm repo add stable https://kubernetes-charts.storage.googleapis.com
            helm repo add jetstack https://charts.jetstack.io
            helm repo add bananaspliff https://bananaspliff.github.io/geek-charts
            helm repo update
      # - run:
      #     name: install rocketchat
      #     command: |
      #       sed -i 's/MONGO_ROOT_PASSWORD/'$MONGO_ROOT_PASSWORD'/g' helm_values/bitwarden.values.yaml
      #       sed -i 's/MONGO_PASSWORD/'$MONGO_PASSWORD'/g' helm_values/bitwarden.values.yaml
      #       sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' helm_values/bitwarden.values.yaml
      #       kubectl apply -f rocketchat/namespace.yaml
      #       kubectl apply -f rocketchat/volumes.yaml
      #       helm upgrade rocketchat stable/rocketchat --values helm_values/rocketchat.values.yaml --namespace rocketchat --install
      #       sleep 10s
      - run:
          name: install metallb
          command: |
            kubectl apply -f metallb/namespace.yaml
            kubectl apply -f metallb/
      - run:
          name: install nginx-ingress
          command: |
            kubectl apply -f nginx-ingress/namespace.yaml
            kubectl apply -f nginx-ingress/
      # - run:
      #     name: install cert-manager
      #     command: |
      #       kubectl apply -f cert-manager/namespace.yaml
      #       kubectl apply -f cert-manager/
      #       helm upgrade cert-manager jetstack/cert-manager --namespace cert-manager --values helm_values/cert-manager.yaml
      #       sleep 10s
      - run:
          name: install nextcloud
          command: |
            sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' nextcloud/ingress.yaml
            sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' nextcloud/nextcloud.deployment.yaml
            sed -i 's/NEXTCLOUD_PASSWORD/'$NEXTCLOUD_PASSWORD'/g' nextcloud/secrets.yaml
            sed -i 's/REDIS_PASSWORD_CLIENT/'$REDIS_PASSWORD_CLIENT'/g' nextcloud/secrets.yaml
            kubectl apply -f nextcloud/namespace.yaml
            kubectl apply -f nextcloud/
            sleep 10s
      - run:
          name: install redis
          command: |
            sed -i 's/REDIS_CONFIG/'$REDIS_CONFIG'/g' redis/redis.yaml
            kubectl apply -f redis/
            sleep 10s
      - run:
          name: install mysql
          command: |
            sed -i 's/MYSQL_ROOT_PASSWORD/'$MYSQL_ROOT_PASSWORD'/g' mariadb/mysql.yaml
            kubectl apply -f redis/
            sleep 10s
      - run:
          name: install kubernetes-dashboard
          command: |
            sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' kubernetes-dashboard/ingress.yaml
            kubectl apply -f kubernetes-dashboard/ -n kubernetes-dashboard
      # - run:
      #     name: install transmission
      #     command: |
      #       sed -i 's/NORDVPN_PASSWORD/'$NORDVPN_PASSWORD'/g' transmission/nordvpn-creds.yaml
      #       sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' transmission/ingress.yaml
      #       kubectl apply -f transmission/namespace.yaml
      #       kubectl apply -f transmission/ -n transmission
      #       helm upgrade transmission bananaspliff/transmission-openvpn --values helm_values/transmission-openvpn.values.yaml --namespace transmission --install
      #       sleep 10s
      - run:
          name: install emby
          command: |
            kubectl apply -f emby/namespace.yaml -n emby
            sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' emby/ingress.yaml
            kubectl apply -f emby/ -n emby
      - run:
          name: install ghost
          command: |
            kubectl apply -f ghost/namespace.yaml -n ghost
            sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' ghost/ingress.yaml
            sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' ghost/deployment.yaml
            kubectl apply -f ghost/ -n ghost
      # - run:
      #     name: install bitwarden
      #     command: |
      #       git clone https://github.com/gjeanmart/bitwarden-k8s.git bitwarden/bitwarden-k8s
      #       sed -i 's/BITWARDEN_ADMIN_PASSWORD/'$BITWARDEN_ADMIN_PASSWORD'/g' helm_values/bitwarden.values.yaml
      #       sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' helm_values/bitwarden.values.yaml
      #       kubectl apply -f bitwarden/namespace.yaml
      #       kubectl apply -f bitwarden/volumes.yaml
      #       helm upgrade bitwarden ./bitwarden/bitwarden-k8s --values helm_values/bitwarden.values.yaml --namespace bitwarden --install
      #       sleep 10s
      # - run:
      #     name: install rocketchat
      #     command: |
      #       sed -i 's/MONGO_ROOT_PASSWORD/'$MONGO_ROOT_PASSWORD'/g' helm_values/rocketchat.values.yaml
      #       sed -i 's/MONGO_PASSWORD/'$MONGO_PASSWORD'/g' helm_values/rocketchat.values.yaml
      #       sed -i 's/DOMAIN_TEMPLATE/'$DOMAIN'/g' helm_values/rocketchat.values.yaml
      #       kubectl apply -f rocketchat/namespace.yaml
      #       kubectl apply -f rocketchat/volumes.yaml
      #       helm upgrade rocketchat stable/rocketchat --values helm_values/rocketchat.values.yaml --namespace rocketchat --install
      #       sleep 10s
workflows:
  version: 2.1
  validate:
    jobs:
      - validate-kubernetes-manifests
      - deploy-kubernetes:
          requires:
            - validate-kubernetes-manifests
          filters:
            branches:
              only: master
