---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: emby
  name: music
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: emby
  name: config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: emby
  name: audiobooks
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Audiobooks"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: emby
  name: new-shows
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Shows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: emby
  name: new-movies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Movies"
