---
# Source: nextcloud/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
        nextcloud-redis-client: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - nextcloud
            topologyKey: kubernetes.io/hostname
      containers:
        - name: nextcloud
          image: "nextcloud:21.0.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: "mysql.mysql.svc.cluster.local:3306"
            - name: OVERWRITEHOST
              value: cloud.DOMAIN_TEMPLATE
            - name: OVERWRITEPROTOCOL
              value: https
            - name: MYSQL_DATABASE
              value: "nextcloud"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db
                  key: db-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db
                  key: db-password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: DOMAIN_TEMPLATE
            - name: NEXTCLOUD_DATA_DIR
              value: "/var/www/html/data"
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: nextcloud-username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: nextcloud-password
            - name: REDIS_HOST
              value: redis.redis.svc.cluster.local
            - name: REDIS_HOST_PORT
              value: "6379"
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: REDIS_PASSWORD
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/
              subPath: root
            - name: nextcloud-data
              mountPath: /var/www/html
              subPath: html
            - name: nextcloud-data
              mountPath: /var/www/html/data
              subPath: data
            - name: nextcloud-data
              mountPath: /var/www/html/config
              subPath: config
            - name: nextcloud-data
              mountPath: /var/www/html/custom_apps
              subPath: custom_apps
            - name: nextcloud-data
              mountPath: /var/www/tmp
              subPath: tmp
            - name: nextcloud-data
              mountPath: /var/www/html/themes
              subPath: themes
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-ssd
      # Will mount configuration files as www-data (id: 33) for nextcloud
      securityContext:
        fsGroup: 33
