---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: nextcloud
data:
  REDIS_PASSWORD: REDIS_PASSWORD_CLIENT
---
apiVersion: v1
kind: Secret
data:
  nextcloud-password: NEXTCLOUD_PASSWORD
  nextcloud-username: YWRtaW4=
metadata:
  name: nextcloud
  namespace: nextcloud
type: Opaque
