---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mysql-data"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/mysql"
# nextcloud.persistentvolumeclaim.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "mysql"
  name: "mysql-data"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"