---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-music
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd1/Music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-shows
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd1/Shows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-movies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 550Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd1/Movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: config
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd1/jellyfin-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: audiobooks
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd1/Audiobooks"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: new-shows
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Shows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: new-movies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Movies"
