---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-music
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Music"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-shows
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Shows"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-movies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 550Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Movies"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/jellyfin-config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jellyfin
  name: jellyfin-audiobooks
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/Audiobooks"
