---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: ghost
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ghost
  name: blog-content
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd2/ghost"
