# controller contains configuration specific to the MetalLB cluster
# controller.
controller:
  image:
    repository: metallb/controller
    tag: v0.9.4
    pullPolicy: IfNotPresent

# speaker contains configuration specific to the MetalLB speaker
# daemonset.
speaker:
  image:
    repository: metallb/speaker
    tag: v0.10.2
    pullPolicy: IfNotPresent
configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 192.168.0.240-192.168.0.250
